config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'admin/index'
  get 'admin/change_number_of_entries/:amount', to: 'admin#change_number_of_entries', as: 'admin_change_number_of_entries'

  resources :accounts
  resources :entries
  resources :recurrent_entries
  resources :categories

  root 'admin#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recurrent_entry.rb
class RecurrentEntry < ApplicationRecord
  belongs_to :category
  belongs_to :account
  belongs_to :user
  has_many :entries, dependent: :nullify

  validates :value, presence: true

  def has_entry_within_month?
    first_day_of_month = Date.parse(Time.now.strftime('%Y/%m/01'))+1.month
    last_day_of_month = first_day_of_month + 1.month - 1.day
    entry = Entry.where("recurrent_entry_id = :recurrent_entry_id and effective_date >= :effective_date_low and effective_date <= :effective_date_high", {recurrent_entry_id: self.id, effective_date_low: first_day_of_month, effective_date_high: last_day_of_month}).first()
    if entry
      return true
    else
      return false
    end
  end

  # def too_early_within_month?
  #   Date.today < new_entry_date ? true : false
  # end

  def create_entry
    entry = Entry.new
    entry.recurrent_entry_id = self.id
    entry.account_id = self.account_id
    entry.category_id = self.category_id
    entry.effective_date = new_entry_date
    entry.checked = self.checked
    entry.comment = self.comment
    entry.value = self.value

    if entry.save
      true
    else
      false
    end
  end

  private
  def new_entry_date
     self.start_date + ((Date.today+1.month).month-(self.start_date).month).month + ((Date.today+1.month).year-(self.start_date).year).year
  end
end

app/controllers/recurrent_entries_controller.rb
class RecurrentEntriesController < ApplicationController
  before_action :set_recurrent_entry, only: [:show, :edit, :update, :destroy]

  # GET /recurrent_entries
  # GET /recurrent_entries.json
  def index
    @recurrent_entries = RecurrentEntry.all
  end

  # GET /recurrent_entries/new
  def new
    @recurrent_entry = RecurrentEntry.new
  end

  # GET /recurrent_entries/1/edit
  def edit
  end

  # POST /recurrent_entries
  def create
    @recurrent_entry = RecurrentEntry.new(reformat_value(recurrent_entry_params))
    @recurrent_entry.user = current_user

    respond_to do |format|
      if @recurrent_entry.save
        format.html { redirect_to recurrent_entries_url, notice: 'Recurrent entry was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /recurrent_entries/1
  def update
    respond_to do |format|
      if @recurrent_entry.update(reformat_value(recurrent_entry_params))
        format.html { redirect_to recurrent_entries_url, notice: 'Recurrent entry was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /recurrent_entries/1
  def destroy
    @recurrent_entry.destroy
    respond_to do |format|
      format.html { redirect_to recurrent_entries_url, notice: 'Recurrent entry was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recurrent_entry
      @recurrent_entry = RecurrentEntry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recurrent_entry_params
      params.require(:recurrent_entry).permit(:active, :user_id, :account_id, :category_id, :checked, :comment, :value, :frequency, :start_date, :end_date)
    end

    # Works only with the 'value' field
    #   Replaces ',' by '.'
    #   Adds '-' when nothing is provided by default
    def reformat_value(params)
      local_params = params
      if (!local_params[:value].to_s.starts_with?("+") && !local_params[:value].to_s.starts_with?("-"))
        local_params[:value] = local_params[:value].to_s.gsub(',', '.').to_f.to_s
        local_params[:value] = - local_params[:value].to_f
      else
        local_params[:value] = local_params[:value].to_s.gsub(',', '.').to_f.to_s
      end
      return local_params
    end
end

app/helpers/recurrent_entries_helper.rb
module RecurrentEntriesHelper
end

app/views/recurrent_entries/_form.html.erb
<%= form_with(model: recurrent_entry, local: true, html: { class: "uk-form-stacked"}) do |form| %>
  <div class="uk-margin">
    <%= form.label :active, class: "uk-form-label" %>
    <%= form.check_box :active, class: "uk-checkbox" %>
  </div>

  <div class="uk-margin">
    <%= form.label :account_id, class: "uk-form-label" %>
    <select class="uk-select" name="recurrent_entry[account_id]" id="recurrent_entry_account_id">
      <%= options_from_collection_for_select(current_user.accounts, :id, :name, recurrent_entry.account_id) %>
    </select>
  </div>

  <div class="uk-margin">
    <%= form.label :category_id, class: "uk-form-label" %>
    <select class="uk-select" name="recurrent_entry[category_id]" id="recurrent_entry_category_id">
      <%= options_from_collection_for_select(current_user.categories, :id, :name, recurrent_entry.category_id) %>
    </select>
  </div>

  <div class="uk-margin">
    <%= form.label :checked, class: "uk-form-label" %>
    <%= form.check_box :checked, class: "uk-checkbox" %>
  </div>

  <div class="uk-margin">
    <%= form.label :comment, class: "uk-form-label" %>
    <%= form.text_field :comment, class: "uk-input" %>
  </div>

  <div class="uk-margin">
    <%= form.label :value, class: "uk-form-label" %>
    <%= form.text_field :value, class: "uk-input" %>
  </div>

  <div class="uk-margin">
    <%= form.label :frequency, class: "uk-form-label" %>
    <%= form.text_field :frequency, class: "uk-input" %>
  </div>

  <div class="uk-margin">
    <%= form.label :start_date, class: "uk-form-label" %>
    <%= form.date_select :start_date %>
  </div>

  <div class="uk-margin">
    <%= form.label :end_date, class: "uk-form-label" %>
    <%= form.date_select :end_date %>
  </div>

  <div class="actions">
    <%= form.submit "Enregistrer", class: "uk-button uk-button-primary"%>
  </div>
<% end %>

app/views/recurrent_entries/edit.html.erb
<div class="uk-position-center">
  <div class="uk-card uk-card-default uk-card-large uk-card-hover">
      <div class="uk-card-header">
        <h1 class="uk-card-title">Modifier la facture périodique</h1>
      </div>
      <div class="uk-card-body">
        <%= render 'form', recurrent_entry: @recurrent_entry %>
        <hr />
        <%= link_to 'Annuler', recurrent_entries_path, class: "uk-button uk-button-default" %>
      </div>
  </div>
</div>

app/views/recurrent_entries/index.html.erb
<div class="mo-secondary">
  <h1 class="uk-h1">Factures périodiques</h1>
  <%= link_to 'Ajouter une facture périodique', new_recurrent_entry_path, class: "uk-button uk-button-primary" %>

  <table class="uk-table uk-table-small uk-table-striped uk-table-hover">
    <thead>
      <tr>
        <th>Compte</th>
        <th>Catégorie</th>
        <th>Montant</th>
        <th>Fréquence</th>
        <th>Du</th>
        <th>Au</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @recurrent_entries.each do |recurrent_entry| %>
        <tr>
          <td><%= recurrent_entry.account.name %></td>
          <td><%= recurrent_entry.category.name %> <span class="uk-label"><%= "Inactif" if !recurrent_entry.active? %></span></td>
          <td><%= formatValue(recurrent_entry.value) %></td>
          <td><%= recurrent_entry.frequency %></td>
          <td><%= recurrent_entry.start_date %></td>
          <td><%= recurrent_entry.end_date %></td>
          <td><%= link_to 'Edit', edit_recurrent_entry_path(recurrent_entry), class: "uk-button uk-button-text" %></td>
          <td><%= link_to 'Destroy', recurrent_entry, method: :delete, class: "uk-button uk-button-text", data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/recurrent_entries/new.html.erb
<div class="uk-position-center">
  <div class="uk-card uk-card-default uk-card-large uk-card-hover">
      <div class="uk-card-header">
        <h1 class="uk-card-title">Ajouter une nouvelle facture périodique</h1>
      </div>
      <div class="uk-card-body">
        <%= render 'form', recurrent_entry: @recurrent_entry %>
        <hr />
        <%= link_to 'Annuler', recurrent_entries_path, class: "uk-button uk-button-default" %>
      </div>
  </div>
</div>