config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'admin/index'
  get 'admin/change_number_of_entries/:amount', to: 'admin#change_number_of_entries', as: 'admin_change_number_of_entries'

  resources :accounts
  resources :entries
  resources :recurrent_entries
  resources :categories

  root 'admin#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_account_entries.html.erb
<div class="mo-current-entries uk-overflow-auto uk-position-top" >
  <% account.entries_up_to_today(@number_of_entries).each do |entry| %>
  <a href="<%= edit_entry_path(entry) %>" class="uk-flex uk-flex-row <%= cycle("om-odd", "om-even") %> <%= 'om-selected' unless (!selected_entry || selected_entry != entry) %>">
    <div class="uk-flex-column mo-checked"><span class="mo-checked-entry <%= entry.checked ? "checked" : "" %>"></span></div>
    <div class="uk-flex-column mo-effective-date"><%= entry.effective_date %></div>
    <div class="uk-flex-column mo-category"><%= entry.category.name %></div>
    <div class="uk-flex-column mo-comment"><%= entry.comment %></div>
    <div class="uk-flex-column mo-check-number" ><span class="uk-label"><%= entry.check_number %></span></div>
    <div class="uk-flex-column mo-label"><span class="uk-label"><%= "Auto" if entry.recurrent_entry_id? %></span></div>
    <div class="uk-flex-column mo-value uk-text-right"><%= formatValue(entry.value) %></div>
  </a>
  <% end %>
</div>
<div class="mo-upcoming-entries-header">
  <div class="mo-solde-futur">Solde futur : <%= formatValue(account.absoluteBanlance) %></div>
</div>
<div class="mo-upcoming-entries uk-height-medium uk-position-bottom uk-overflow-auto">
  <% account.entries_after_today.each do |entry| %>
  <a href="<%= edit_entry_path(entry) %>" class="uk-flex uk-flex-row <%= cycle("om-odd", "om-even") %> <%= 'om-selected' unless (!selected_entry || selected_entry != entry) %>">
    <div class="uk-flex-column mo-checked"><span class="mo-checked-entry <%= entry.checked ? "checked" : "" %>"></span></div>
    <div class="uk-flex-column mo-effective-date"><%= entry.effective_date %></div>
    <div class="uk-flex-column mo-category"><%= entry.category.name %></div>
    <div class="uk-flex-column mo-comment"><%= entry.comment %></div>
    <div class="uk-flex-column mo-check-number" ><span class="uk-label"><%= entry.check_number %></span></div>
    <div class="uk-flex-column mo-label"><span class="uk-label"><%= "Auto" if entry.recurrent_entry_id? %></span></div>
    <div class="uk-flex-column mo-value uk-text-right"><%= formatValue(entry.value) %></div>
  </a>
  <% end %>
</div>

app/views/shared/_account_header.html.erb
<nav class="mo-account-header">
  <h1 class="uk-h1"><%= account.name %></h1>
  <div class="mo-solde-total">Solde : <%= formatValue(account.currentBanlance) %></div>
  <div class="mo-links">
    <ul>
      <li><%= link_to 'Télécharger CSV', account_path(account, :format => "csv"), class: "uk-button uk-button-text" %></li>
      <li><%= link_to 'Renommer', edit_account_path(account), class: "uk-button uk-button-text" %></li>
      <li><%= link_to 'Supprimer', account, method: :delete, class: "uk-button uk-button-text", data: { confirm: 'Are you sure?' } %></li>
    </ul>
  </div>
  <div class="mo-settings">
    <div class="uk-inline">
        <span class="mo-label">Afficher les</span><button type="button" class="uk-button uk-button-small uk-button-default"><%= NUMBER_OF_ENTRIES_OPTIONS[@number_of_entries] %></button>
        <div uk-dropdown="mode: click ; pos: bottom-right">
          <ul class="uk-nav uk-dropdown-nav">
            <% NUMBER_OF_ENTRIES_OPTIONS.each do |key, choice| %>
              <li><%= link_to choice, admin_change_number_of_entries_url(key) %></li>
            <% end %>
          </ul>
        </div>
    </div>
  </div>
</nav>

app/views/shared/_entry_editor.html.erb
<div class="uk-card uk-card-default">
    <div class="uk-card-header">
      <% if entry.id.nil? %>
      <h3 class="uk-h3">Ajouter une entrée</h3>
      <% else %>
      <h3 class="uk-h3">Modifier une entrée</h3>
      <% end %>
    </div>
    <div class="uk-card-body">
        <%= render 'entries/form', entry: entry, account: account %>
    </div>
</div>