config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'admin/index'
  get 'admin/change_number_of_entries/:amount', to: 'admin#change_number_of_entries', as: 'admin_change_number_of_entries'

  resources :accounts
  resources :entries
  resources :recurrent_entries
  resources :categories

  root 'admin#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneyFlornetFr</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="uk-height-1-1">
    <% if current_user %>
    <div class="mo-sidebar-left uk-height-1-1">
      <ul class="uk-nav uk-navbar-dropdown-nav">
        <li class="uk-nav-header">Comptes</li>
        <% current_user.accounts.each do |account| %>
          <li class="<%= uk_active_selected_account?(@current_account, account) %>"><%= link_to account.name, account %></li>
        <% end %>
        <li class="<%= uk_active_url?(new_account_path) %>"><%= link_to 'Créer un nouveau compte', new_account_path %></li>

        <li class="uk-nav-header">Paramétrages</li>
        <li class="mo-first-settings-entry <%= uk_active_url?(recurrent_entries_path) %>"><%= link_to "Factures périodiques", recurrent_entries_url %></li>
        <li class="<%= uk_active_url?(categories_path) %>"><%= link_to "Catégories", categories_url %></li>
      </ul>

      <div class="uk-position-bottom-left mo-user-account">
        <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, :class => 'uk-link-muted'  %> (<%= current_user.email %>)
      </div>

    </div>
    <% end %>
    <div class="mo-main uk-height-1-1" uk-height-viewport>
        <% if notice %>
        <div class="uk-alert-success" uk-alert>
            <a class="uk-alert-close" uk-close></a>
            <%= notice %>
        </div>
        <% end %>
        <% if alert %>
        <div class="uk-alert-danger" uk-alert>
            <a class="uk-alert-close" uk-close></a>
            <%= alert %>
        </div>
        <% end %>

        <%= yield %>
    </div>
  </body>
</html>